[additional_network_arguments]
unet_lr            = 2e-6
train_text_encoder = true
learning_rate_te1 = 4e-7
learning_rate_te2 = 6e-7


[optimizer_arguments]
model_train_type = "sdxl-finetune"
max_train_epochs    = 11
protected_tags_file = "F:/Software/lora-scripts/config/protected.txt"
loss_type          = "l2"
save_every_n_epochs = 2
train_batch_size   = 1
max_grad_norm      = 1
weighted_captions  = false
seed               = 1234
max_token_length   = 225
lowram             = false
max_data_loader_n_workers = 4
persistent_data_loader_workers = true
save_precision     = "bf16"
mixed_precision    = "bf16"
full_bf16          = false
output_dir         = "F:/Software/lora-scripts/output"
output_name        = "rd-rf"
noise_offset = 0.05
multires_noise_iterations = 8
multires_noise_discount = 0.2
sample_sampler = "euler_a"
sample_every_n_epochs = 2
sample_prompts = "F:/Software/lora-scripts/config/sample_prompts.txt"

[training_arguments]

output_dir         = "F:/Software/lora-scripts/output"
output_name        = "rf-rurudo"


[model_arguments]
pretrained_model_name_or_path = "F:/下载资源/Illustrious-XL-v2.0.safetensors" #OwO
vae = "F:/Software/lora-scripts/sd-models/EQB7DecB2.safetensors"
v2                    = false
sdxl                  = true
gradient_checkpointing = true
gradient_accumulation_steps = 1
sdpa                  = false
xformers              = true
#logging_dir ="logs"
#log_with = "wandb"
#wandb_run_name = "Chenkin-RF-0.3"
[saving_arguments]
save_model_as = "safetensors"


[dataset_arguments]
cache_latents              = true
cache_latents_to_disk      = true
lr_warmup_steps            = 1900

#edm2_loss_weighting = true
#edm2_loss_weighting_optimizer = "torch.optim.AdamW"
#edm2_loss_weighting_optimizer_lr = "7e-3"
#edm2_loss_weighting_optimizer_args = "{'weight_decay':5e-3}"
#edm2_loss_weighting_lr_scheduler = true
#edm2_loss_weighting_lr_scheduler_warmup_percent = 0.1
#edm2_loss_weighting_lr_scheduler_constant_percent = 0.9
#edm2_loss_weighting_generate_graph = true
#edm2_loss_weighting_generate_graph_output_dir = "/workspace/bluvoll/edm2tests"
#edm2_loss_weighting_generate_graph_every_x_steps = 10
#edm2_loss_weighting_generate_graph_y_limit = 40
#edm2_loss_weighting_initial_weights = ""
#edm2_loss_weighting_num_channels = 448