[additional_network_arguments]
unet_lr            = 2e-6
train_text_encoder = true
learning_rate_te1 = 4e-7
learning_rate_te2 = 5e-7

[optimizer_arguments]
lr_scheduler       = "cosine_with_restart"
lr_scheduler_num_cycles = 5
optimizer_type     = "Lion"
optimizer_args     = ["weight_decay=0.01", "betas=0.9,0.99"]
min_lr             = 0

[training_arguments]
model_train_type = "sdxl-finetune"
train_data_dir = "D:/[01]-Entertainment/[01]-AITest/训练集等/rurudo-traindata-20250120/train"
max_train_epochs    = 14
protected_tags_file = "F:/Software/lora-scripts/config/protected.txt"
esolution = "2048,2048"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2880
bucket_reso_steps = 32
save_every_n_epochs = 3
train_batch_size   = 1
max_grad_norm      = 1
weighted_captions  = false
seed               = 845
resolution = "1536,1536"
max_token_length   = 225
lowram             = false
max_data_loader_n_workers = 4
persistent_data_loader_workers = true
save_precision     = "bf16"
mixed_precision    = "bf16"
full_bf16          = false
output_dir         = "F:/Software/lora-scripts/output"
output_name        = "rd-rf"
noise_offset = 0.05
multires_noise_iterations = 8
multires_noise_discount = 0.2
sample_sampler = "euler_a"
sample_every_n_epochs = 2
sample_prompts = "F:/Software/lora-scripts/config/sample_prompts.txt"
log_with = "tensorboard"
log_tracker_name = "rrd"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
weighted_captions = false
keep_tokens = 2
max_token_length = 225
no_token_padding = false

[model_arguments]
pretrained_model_name_or_path = "F:/下载资源/Illustrious-XL-v2.0.safetensors" #OwO
vae = "F:/Software/lora-scripts/sd-models/EQB7DecB2.safetensors"
v2                    = false
sdxl                  = true
gradient_checkpointing = true
gradient_accumulation_steps = 1
xformers = true

[saving_arguments]
save_model_as = "safetensors"


[dataset_arguments]
cache_latents              = true
cache_latents_to_disk      = true
lr_warmup_steps            = 2350
